spring:
  datasource:
    generate-unique-name: false
    name: testdb
    hikari:
      maximum-pool-size: 5
      connection-timeout: 600000
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  error:
    include-stacktrace: never
    include-message: always
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      springframework:
#        jdbc:
#          datasource:
#            init:
#              ScriptUtils: DEBUG




springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
    default-models-expand-depth: -1
  show-actuator: true